---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-plus-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/nginx-plus-ingress
    repoURL: https://github.com/gkor75/modern_app_jumpstart_workshop_infra.git
    targetRevision: gk
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
